[package]
name = "small_http"
version = "0.1.0"
authors = ["UA3MQJ <ua3mqj@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "2"
actix-rt = "1"